# Generated by Django 4.2.3 on 2023-07-18 11:38

import crm_offices.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(crm_offices.utils.CustomStr, models.Model),
        ),
    ]
