# Generated by Django 4.2.3 on 2023-07-18 13:26

import crm_offices.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа расхода')),
            ],
            bases=(crm_offices.utils.CustomStr, models.Model),
        ),
        migrations.AddField(
            model_name='employees',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='employees',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='employees',
            name='name',
            field=models.CharField(default=1, verbose_name='ФИО сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='phone',
            field=models.CharField(default=1, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(default=120000, verbose_name='Зарплата'),
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название пункта')),
                ('address', models.CharField(verbose_name='Адрес')),
                ('phone', models.CharField(verbose_name='Телефон')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата добавления')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office', to=settings.AUTH_USER_MODEL, verbose_name='Администратор пункта')),
            ],
            bases=(crm_offices.utils.CustomStr, models.Model),
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата штрафа')),
                ('amount', models.IntegerField(verbose_name='Сумма штрафа')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='crm.employees', verbose_name='Сотрудник')),
            ],
            bases=(crm_offices.utils.CustomStr, models.Model),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата расхода')),
                ('amount', models.IntegerField(verbose_name='Сумма расхода')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='crm.expensestypes', verbose_name='Тип расхода')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='crm.offices', verbose_name='Офис')),
            ],
            bases=(crm_offices.utils.CustomStr, models.Model),
        ),
        migrations.AddField(
            model_name='employees',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.offices', verbose_name='Пункт'),
        ),
    ]
