# Generated by Django 4.2.3 on 2023-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_expensestypes_employees_comment_employees_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='expensestypes',
            options={'verbose_name': 'Тип расхода', 'verbose_name_plural': 'Типы расходов'},
        ),
        migrations.AlterModelOptions(
            name='fines',
            options={'verbose_name': 'Штраф', 'verbose_name_plural': 'Штрафы'},
        ),
        migrations.AlterModelOptions(
            name='offices',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Пункты'},
        ),
        migrations.AddField(
            model_name='offices',
            name='slug',
            field=models.SlugField(default=1, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
