# Generated by Django 4.2.3 on 2023-07-19 12:57

import crm_offices.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_employees_options_alter_expenses_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Валюта')),
                ('symbol', models.CharField(verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
            bases=(crm_offices.utils.CustomStr, models.Model),
        ),
        migrations.AddField(
            model_name='expenses',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='crm.currency', verbose_name='Валюта'),
        ),
    ]
