# Generated by Django 4.2.3 on 2023-07-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_expenses_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='crm.currency', verbose_name='Валюта'),
        ),
    ]
