# Generated by Django 4.2.3 on 2023-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_expenses_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offices',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
