# Generated by Django 4.2.3 on 2023-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_salaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fines',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
