# Generated by Django 4.2.3 on 2023-07-31 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_fines_comment_alter_salaries_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offices',
            name='phone',
        ),
    ]
