version: "3.10"

services:
  db_postgres:
    image: postgres:15
    container_name: db_postgres
    volumes:
      - ~/.pg/pg_data/crm:/var/lib/postgresql/data
    env_file:
      - .env
  crm_offices:
    image: crm_offices:latest
    container_name: crm_offices
    depends_on:
      - db_postgres
    volumes:
      - static_volume:/crm/static
      - media_volume:/crm/media
    env_file:
      - .env
    command:
      bash -c "./manage.py collectstatic --noinput && sleep 30 && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 crm_offices.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: crm_nginx
    image: crm_nginx
    volumes:
      - static_volume:/crm/static
      - media_volume:/crm/media
    depends_on:
      - crm_offices
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"



volumes:
  static_volume:
  media_volume:
